// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getShape
std::string getDNAShape(std::string fastaFilePath, std::string shapeType);
RcppExport SEXP DNAshapeR_getShape(SEXP fastaFilePathSEXP, SEXP shapeTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fastaFilePath(fastaFilePathSEXP);
    Rcpp::traits::input_parameter< std::string >::type shapeType(shapeTypeSEXP);
    __result = Rcpp::wrap(getShape(fastaFilePath, shapeType));
    return __result;
END_RCPP
}
