// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getDNAShape
std::string getDNAShape(std::string fastaFilePath, std::string shapeType);
RcppExport SEXP DNAshapeR_getDNAShape(SEXP fastaFilePathSEXP, SEXP shapeTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fastaFilePath(fastaFilePathSEXP);
    Rcpp::traits::input_parameter< std::string >::type shapeType(shapeTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(getDNAShape(fastaFilePath, shapeType));
    return rcpp_result_gen;
END_RCPP
}
